### ISSUE TITLE
10.11.4

### ISSUE THREAD

**Issue by dyeazel** [rthomson/isight-disabler#4]
Not working on 10.11.4.

**Comment by rthomson** [comment]
Did you run the AppleScript as-is or use the profile-based approach?

**Comment by dyeazel** [comment]
I tried both. It wasn't clear exactly how to use it. 

Enviado desde mi iPhone

**Comment by rthomson** [comment]
The traditional or legacy AppleScript method is less convenient since Apple introduced [System Integrity Protection](https://support.apple.com/en-us/HT204899) (SIP) in 10.11. To use the AppleScript on modern macOS systems, you essentially have to disable SIP to run the AppleScript. However, it's probably best to keep SIP enabled most of the time so that turns into a dance of disabling SIP, running the AppleScript and then enabling SIP again.

The [configuration profile or "mobileconfig"](https://github.com/rthomson/isight-disabler/blob/master/camera-disabler.mobileconfig) option is the recommended way to disable the camera on modern macOS. See [Apple documentation on managing configuration profiles](https://support.apple.com/kb/PH22006?locale=en_US) for details on how to install or remove the camera-disabler.mobileconfig profile.
