### ISSUE TITLE
Upgraded to Catalina, can't re-enable

### ISSUE THREAD

**Issue by GrapeJelly** [rthomson/isight-disabler#9]
I used iSight Disabler on an older version of my OS and now I can't undo it. Is there a way to enable it again in Catalina?

**Comment by rthomson** [comment]
The original iSight Disabler worked by modifying file system permissions. Modern versions of macOS made that approach difficult to manage due to SIP (https://support.apple.com/en-us/HT204899) and unnecessary due to the inclusion of camera settings in mobileconfig profiles which provides the effectively the same functionality as iSight Disabler.

One possible approach to solving your problem is by attempting a permissions repair on your system disk with Disk Utility similar to this: https://pdf.wondershare.com/macos-10-15/repair-disk-permissions-on-macos-10-15.html. I don't know if this will work. Repair permissions at your own risk.

Alternatively, you can try to run iSight Disabler to enable your camera with SIP temporarily disabled (https://www.imore.com/how-turn-system-integrity-protection-macos). Make sure you turn SIP back on again after you're done "enabling" your camera. Again, at your own risk.

**Comment by GrapeJelly** [comment]
Thanks for the quick reply. I tried both of those things and neither worked. For the second one I got an error popup that read:

> profiles remove for identifier:'com.app.mdm.mba.........alacarte' and user:'root' returned -205 (Unable to locate configuration profile.)

**Comment by noahmaranesi** [comment]
I updated to macOS Big Sur and unfortunately some more work will be required. I can't remember when I used this utility/script to disable the iSight camera but it was probably macOS Mojave.

I was unable to re-enable the iSight camera with SIP disabled, even when logged in as root user, and repairing permissions in Recovery OS (recovery mode) did not work either.

It’s understood that the traditional script is no longer maintained due to the restrictions and limitations placed by macOS, but I thought I’d share this error message too I received. I get no error message when clicking “Disable” (probably because there’s no permission to change since it’s already disabled), this error message shows when clicking “Enable”.

Now I basically have a non-functioning iSight camera. It’s obviously only my fault, but I would still like to get it fixed!

<img src="https://user-images.githubusercontent.com/12670516/102448966-5a056e00-4087-11eb-8f18-fe5a747b6cfe.png" width="100%">

Additionally, downloading and attempting to install [`camera-disabler.mobileconfig`](https://github.com/rthomson/isight-disabler/blob/master/camera-disabler.mobileconfig) does nothing either. All I get is a notification and macOS seems to do nothing about it; clicking on the notification doesn’t take me to System Preferences, and even when it’s open, it doesn’t redirect me.

<img src="https://user-images.githubusercontent.com/12670516/102449860-4955f780-4089-11eb-8cb4-af35caf39db4.png" width="50%">

**Comment by GrapeJelly** [comment]
I ended up wiping my computer and reinstalling the oldest version of MacOS I could, then I upgraded to Catalin again. The iSight works now.

**Comment by alexmamina** [comment]
I had the same issue, but this disabler was a part of an app called Barrier. I did manage to fix it by deleting the profile that the app installed on my computer, then restarting. Now the camera works perfectly

**Comment by rthomson** [comment]
Reported resolved by re-installing macOS.
